[package]
name = "{{name}}"
version = "0.1.0"
edition = "2021"
description = "A placeholder crate to reserve this name"
repository = "{{repo}}"
license = "MIT"
{{#if author}}
authors = ["{{author}}"]
{{/if}}

